[2025-05-13T22:49:32.188+0000] {processor.py:157} INFO - Started process (PID=420) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:49:32.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:49:32.190+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:49:32.189+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:49:32.195+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:49:32.194+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:49:32.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:49:32.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.020 seconds
[2025-05-13T22:50:02.517+0000] {processor.py:157} INFO - Started process (PID=430) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:50:02.518+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:50:02.519+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:50:02.518+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:50:02.524+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:50:02.523+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:50:02.525+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:50:02.538+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.025 seconds
[2025-05-13T22:50:32.849+0000] {processor.py:157} INFO - Started process (PID=440) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:50:32.851+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:50:32.853+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:50:32.852+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:50:32.861+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:50:32.860+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:50:32.862+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:50:32.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.038 seconds
[2025-05-13T22:51:03.156+0000] {processor.py:157} INFO - Started process (PID=450) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:51:03.157+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:51:03.159+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:51:03.158+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:51:03.167+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:51:03.166+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:51:03.167+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:51:03.178+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.024 seconds
[2025-05-13T22:51:33.462+0000] {processor.py:157} INFO - Started process (PID=460) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:51:33.463+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:51:33.464+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:51:33.464+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:51:33.472+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:51:33.471+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:51:33.472+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:51:33.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.032 seconds
[2025-05-13T22:52:03.851+0000] {processor.py:157} INFO - Started process (PID=470) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:52:03.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:52:03.853+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:52:03.852+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:52:03.857+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:52:03.857+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:52:03.858+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:52:03.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.024 seconds
[2025-05-13T22:52:34.173+0000] {processor.py:157} INFO - Started process (PID=480) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:52:34.174+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:52:34.175+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:52:34.175+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:52:34.182+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:52:34.181+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:52:34.183+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:52:34.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.028 seconds
[2025-05-13T22:53:04.465+0000] {processor.py:157} INFO - Started process (PID=490) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:53:04.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:53:04.468+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:53:04.468+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:53:04.476+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:53:04.475+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:53:04.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:53:04.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.033 seconds
[2025-05-13T22:53:34.786+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:53:34.788+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:53:34.789+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:53:34.788+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:53:34.796+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:53:34.795+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:53:34.796+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:53:34.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.024 seconds
[2025-05-13T22:54:05.068+0000] {processor.py:157} INFO - Started process (PID=510) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:54:05.069+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:54:05.070+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:54:05.070+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:54:05.075+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:54:05.074+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:54:05.075+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:54:05.087+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.021 seconds
[2025-05-13T22:54:35.370+0000] {processor.py:157} INFO - Started process (PID=520) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:54:35.372+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:54:35.373+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:54:35.372+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:54:35.380+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:54:35.378+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:54:35.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:54:35.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.031 seconds
[2025-05-13T22:55:05.724+0000] {processor.py:157} INFO - Started process (PID=530) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:55:05.725+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:55:05.726+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:55:05.725+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:55:05.732+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:55:05.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:55:05.732+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:55:05.745+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.025 seconds
[2025-05-13T22:55:36.070+0000] {processor.py:157} INFO - Started process (PID=540) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:55:36.071+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:55:36.073+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:55:36.072+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:55:36.079+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:55:36.078+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:55:36.080+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:55:36.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.032 seconds
[2025-05-13T22:56:06.390+0000] {processor.py:157} INFO - Started process (PID=550) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:56:06.391+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:56:06.392+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:56:06.392+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:56:06.398+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:56:06.397+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:56:06.399+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:56:06.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.032 seconds
[2025-05-13T22:56:36.721+0000] {processor.py:157} INFO - Started process (PID=560) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:56:36.723+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:56:36.724+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:56:36.723+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:56:36.731+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:56:36.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:56:36.733+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:56:36.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.038 seconds
[2025-05-13T22:57:07.067+0000] {processor.py:157} INFO - Started process (PID=570) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:57:07.069+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:57:07.070+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:57:07.069+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:57:07.077+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:57:07.076+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:57:07.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:57:07.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.031 seconds
[2025-05-13T22:57:37.410+0000] {processor.py:157} INFO - Started process (PID=580) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:57:37.412+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:57:37.413+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:57:37.413+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:57:37.420+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:57:37.419+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:57:37.420+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:57:37.437+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.033 seconds
[2025-05-13T22:58:07.757+0000] {processor.py:157} INFO - Started process (PID=590) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:58:07.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:58:07.760+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:58:07.760+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:58:07.763+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:58:07.763+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:58:07.764+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:58:07.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.020 seconds
[2025-05-13T22:58:38.085+0000] {processor.py:157} INFO - Started process (PID=600) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:58:38.086+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:58:38.086+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:58:38.086+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:58:38.090+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:58:38.090+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:58:38.091+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:58:38.103+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.021 seconds
[2025-05-13T22:59:08.387+0000] {processor.py:157} INFO - Started process (PID=610) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:08.388+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:59:08.389+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:59:08.388+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:08.394+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:59:08.393+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 10, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:59:08.395+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:08.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.027 seconds
[2025-05-13T22:59:18.499+0000] {processor.py:157} INFO - Started process (PID=615) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:18.500+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:59:18.501+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:59:18.501+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:18.506+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T22:59:18.509+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:59:18.508+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:59:18.509+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:18.525+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.030 seconds
[2025-05-13T22:59:46.391+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:46.392+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T22:59:46.393+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:59:46.393+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:46.395+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T22:59:46.397+0000] {logging_mixin.py:154} INFO - [2025-05-13T22:59:46.396+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T22:59:46.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T22:59:46.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.022 seconds
[2025-05-13T23:00:16.701+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:00:16.703+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:00:16.704+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:00:16.704+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:00:16.709+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:00:16.713+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:00:16.711+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:00:16.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:00:16.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.042 seconds
[2025-05-13T23:00:47.055+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:00:47.056+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:00:47.057+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:00:47.057+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:00:47.061+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:00:47.064+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:00:47.063+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:00:47.064+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:00:47.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.031 seconds
[2025-05-13T23:01:17.394+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:01:17.395+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:01:17.396+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:01:17.396+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:01:17.401+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:01:17.403+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:01:17.402+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:01:17.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:01:17.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.033 seconds
[2025-05-13T23:01:47.785+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:01:47.787+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:01:47.789+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:01:47.788+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:01:47.794+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:01:47.797+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:01:47.795+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:01:47.798+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:01:47.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.039 seconds
[2025-05-13T23:02:18.148+0000] {processor.py:157} INFO - Started process (PID=215) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:02:18.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:02:18.150+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:02:18.150+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:02:18.154+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:02:18.157+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:02:18.156+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:02:18.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:02:18.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.031 seconds
[2025-05-13T23:02:48.506+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:02:48.507+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:02:48.509+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:02:48.509+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:02:48.513+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:02:48.516+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:02:48.515+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:02:48.516+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:02:48.534+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.032 seconds
[2025-05-13T23:03:18.825+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:03:18.827+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:03:18.828+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:03:18.827+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:03:18.831+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:03:18.834+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:03:18.832+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:03:18.834+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:03:18.849+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.029 seconds
[2025-05-13T23:03:49.169+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:03:49.170+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:03:49.171+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:03:49.170+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:03:49.173+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:03:49.175+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:03:49.174+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:03:49.175+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:03:49.186+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.021 seconds
[2025-05-13T23:04:19.482+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:04:19.483+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:04:19.485+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:04:19.484+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:04:19.488+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:04:19.490+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:04:19.489+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:04:19.491+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:04:19.506+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.027 seconds
[2025-05-13T23:04:49.871+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:04:49.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:04:49.873+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:04:49.873+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:04:49.878+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:04:49.882+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:04:49.881+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:04:49.883+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:04:49.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.036 seconds
[2025-05-13T23:05:20.225+0000] {processor.py:157} INFO - Started process (PID=275) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:20.226+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:05:20.227+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:20.227+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:20.231+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:05:20.233+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:20.232+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:05:20.233+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:20.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.026 seconds
[2025-05-13T23:05:50.578+0000] {processor.py:157} INFO - Started process (PID=285) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:50.579+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:05:50.580+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:50.580+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:50.585+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:05:50.587+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:50.586+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_redfin_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_redfin_to_s3.py", line 13, in <module>
    from data.upload_to_s3 import upload_file_to_s3  # ✅ Reuse your real function
ModuleNotFoundError: No module named 'data'
[2025-05-13T23:05:50.588+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:50.603+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.030 seconds
[2025-05-13T23:05:56.692+0000] {processor.py:157} INFO - Started process (PID=295) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:56.693+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:05:56.694+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:56.693+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:56.698+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:05:56.700+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:05:56.707+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:05:56.821+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:56.821+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-13T23:05:56.825+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:56.825+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-13T23:05:56.827+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:56.827+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-13T23:05:56.827+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:56.827+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:05:56.832+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:56.832+0000] {dag.py:2963} INFO - Creating ORM DAG for upload_local_to_s3
[2025-05-13T23:05:56.832+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:05:56.832+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:05:56.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.150 seconds
[2025-05-13T23:06:27.019+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:06:27.020+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:06:27.021+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:06:27.021+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:06:27.027+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:06:27.028+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:06:27.037+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:06:27.055+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:06:27.055+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:06:27.061+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:06:27.061+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:06:27.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.055 seconds
[2025-05-13T23:06:57.349+0000] {processor.py:157} INFO - Started process (PID=315) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:06:57.350+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:06:57.351+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:06:57.351+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:06:57.355+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:06:57.356+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:06:57.362+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:06:57.375+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:06:57.375+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:06:57.381+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:06:57.381+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:06:57.394+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.049 seconds
[2025-05-13T23:07:28.937+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:07:28.938+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:07:28.938+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:07:28.938+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:07:28.940+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:07:28.941+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:07:28.949+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:07:28.961+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:07:28.961+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:07:28.967+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:07:28.966+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:07:28.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.040 seconds
[2025-05-13T23:07:59.223+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:07:59.225+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:07:59.226+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:07:59.226+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:07:59.231+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:07:59.232+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:07:59.243+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:07:59.270+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:07:59.270+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:07:59.276+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:07:59.276+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:07:59.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.067 seconds
[2025-05-13T23:08:29.643+0000] {processor.py:157} INFO - Started process (PID=186) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:08:29.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:08:29.646+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:08:29.646+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:08:29.650+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:08:29.652+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:08:29.662+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:08:29.679+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:08:29.679+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:08:29.686+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:08:29.686+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:08:29.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.056 seconds
[2025-05-13T23:09:00.005+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:09:00.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:09:00.007+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:09:00.007+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:09:00.012+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:09:00.013+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:09:00.023+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:09:00.040+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:09:00.040+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:09:00.047+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:09:00.047+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:09:00.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.056 seconds
[2025-05-13T23:09:30.430+0000] {processor.py:157} INFO - Started process (PID=206) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:09:30.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:09:30.433+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:09:30.432+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:09:30.437+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:09:30.439+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:09:30.448+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:09:30.465+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:09:30.465+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:09:30.472+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:09:30.472+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:09:30.480+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.056 seconds
[2025-05-13T23:10:00.854+0000] {processor.py:157} INFO - Started process (PID=216) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:10:00.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:10:00.856+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:10:00.856+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:10:00.861+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:10:00.863+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:10:00.874+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:10:00.891+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:10:00.891+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:10:00.899+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:10:00.899+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:10:00.907+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.060 seconds
[2025-05-13T23:10:31.271+0000] {processor.py:157} INFO - Started process (PID=226) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:10:31.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:10:31.273+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:10:31.273+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:10:31.278+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:10:31.279+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:10:31.287+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:10:31.304+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:10:31.304+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:10:31.311+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:10:31.311+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:10:31.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.054 seconds
[2025-05-13T23:11:01.692+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:11:01.694+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:11:01.695+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:11:01.695+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:11:01.700+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:11:01.701+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:11:01.709+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:11:01.727+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:11:01.726+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:11:01.734+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:11:01.734+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:11:01.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.055 seconds
[2025-05-13T23:11:32.029+0000] {processor.py:157} INFO - Started process (PID=246) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:11:32.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:11:32.031+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:11:32.031+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:11:32.033+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:11:32.034+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:11:32.040+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:11:32.055+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:11:32.055+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:11:32.061+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:11:32.061+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:11:32.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.043 seconds
[2025-05-13T23:12:02.389+0000] {processor.py:157} INFO - Started process (PID=256) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:12:02.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:12:02.391+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:12:02.391+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:12:02.396+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:12:02.398+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:12:02.407+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:12:02.426+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:12:02.426+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:12:02.433+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:12:02.433+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:12:02.441+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.059 seconds
[2025-05-13T23:12:32.776+0000] {processor.py:157} INFO - Started process (PID=266) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:12:32.777+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:12:32.779+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:12:32.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:12:32.784+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:12:32.785+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:12:32.794+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:12:32.811+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:12:32.811+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:12:32.819+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:12:32.819+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:12:32.828+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.058 seconds
[2025-05-13T23:13:03.196+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:13:03.198+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:13:03.199+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:13:03.199+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:13:03.204+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:13:03.205+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:13:03.216+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:13:03.233+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:13:03.233+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:13:03.241+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:13:03.241+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:13:03.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.059 seconds
[2025-05-13T23:13:33.683+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:13:33.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:13:33.685+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:13:33.685+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:13:33.690+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:13:33.692+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:13:33.701+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:13:33.718+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:13:33.718+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:13:33.725+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:13:33.725+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:13:33.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.056 seconds
[2025-05-13T23:14:04.067+0000] {processor.py:157} INFO - Started process (PID=296) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:14:04.067+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:14:04.068+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:14:04.068+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:14:04.070+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:14:04.071+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:14:04.075+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:14:04.088+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:14:04.088+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:14:04.094+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:14:04.094+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:14:04.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.040 seconds
[2025-05-13T23:14:34.545+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:14:34.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:14:34.547+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:14:34.547+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:14:34.552+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:14:34.554+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:14:34.563+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:14:34.580+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:14:34.579+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:14:34.586+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:14:34.586+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:14:34.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.055 seconds
[2025-05-13T23:15:05.029+0000] {processor.py:157} INFO - Started process (PID=316) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:15:05.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:15:05.032+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:15:05.032+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:15:05.037+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:15:05.039+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:15:05.048+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:15:05.066+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:15:05.066+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:15:05.073+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:15:05.073+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:15:05.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.059 seconds
[2025-05-13T23:15:35.430+0000] {processor.py:157} INFO - Started process (PID=326) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:15:35.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:15:35.433+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:15:35.432+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:15:35.437+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:15:35.438+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:15:35.448+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:15:35.465+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:15:35.465+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:15:35.472+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:15:35.472+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:15:35.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.056 seconds
[2025-05-13T23:16:05.892+0000] {processor.py:157} INFO - Started process (PID=336) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:16:05.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:16:05.895+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:16:05.894+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:16:05.899+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:16:05.900+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:16:05.910+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:16:05.930+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:16:05.930+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:16:05.937+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:16:05.937+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:16:05.945+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.059 seconds
[2025-05-13T23:16:36.354+0000] {processor.py:157} INFO - Started process (PID=346) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:16:36.355+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:16:36.356+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:16:36.356+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:16:36.361+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:16:36.363+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:16:36.372+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:16:36.391+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:16:36.391+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:16:36.398+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:16:36.398+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:16:36.407+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.058 seconds
[2025-05-13T23:17:06.816+0000] {processor.py:157} INFO - Started process (PID=356) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:17:06.817+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:17:06.819+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:17:06.818+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:17:06.824+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:17:06.827+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:17:06.836+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:17:06.854+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:17:06.854+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:17:06.862+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:17:06.862+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:17:06.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.062 seconds
[2025-05-13T23:17:37.316+0000] {processor.py:157} INFO - Started process (PID=366) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:17:37.317+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:17:37.319+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:17:37.318+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:17:37.323+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:17:37.325+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:17:37.333+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:17:37.350+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:17:37.350+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:17:37.357+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:17:37.357+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:17:37.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.055 seconds
[2025-05-13T23:18:07.791+0000] {processor.py:157} INFO - Started process (PID=376) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:18:07.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:18:07.794+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:18:07.793+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:18:07.799+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:18:07.800+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:18:07.810+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:18:07.828+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:18:07.828+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:18:07.836+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:18:07.835+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:18:07.844+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.059 seconds
[2025-05-13T23:22:01.201+0000] {processor.py:157} INFO - Started process (PID=388) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:22:01.202+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:22:01.205+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:22:01.205+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:22:01.215+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:22:01.217+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:22:01.230+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:22:01.272+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:22:01.272+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:22:01.290+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:22:01.290+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:22:01.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.131 seconds
[2025-05-13T23:22:31.621+0000] {processor.py:157} INFO - Started process (PID=398) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:22:31.623+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:22:31.624+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:22:31.624+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:22:31.629+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:22:31.631+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:22:31.644+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:22:31.668+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:22:31.668+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:22:31.677+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:22:31.677+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:22:31.690+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.074 seconds
[2025-05-13T23:23:02.028+0000] {processor.py:157} INFO - Started process (PID=408) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:23:02.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:23:02.031+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:23:02.031+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:23:02.036+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:23:02.038+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:23:02.050+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:23:02.071+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:23:02.071+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:23:02.078+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:23:02.078+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:23:02.088+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.067 seconds
[2025-05-13T23:23:32.393+0000] {processor.py:157} INFO - Started process (PID=418) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:23:32.395+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:23:32.396+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:23:32.395+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:23:32.399+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:23:32.401+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:23:32.410+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:23:32.430+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:23:32.430+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:23:32.439+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:23:32.439+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:23:32.450+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.061 seconds
[2025-05-13T23:24:02.782+0000] {processor.py:157} INFO - Started process (PID=428) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:24:02.784+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:24:02.786+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:24:02.785+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:24:02.790+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:24:02.793+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:24:02.805+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:24:02.825+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:24:02.825+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:24:02.833+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:24:02.833+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:24:02.841+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.065 seconds
[2025-05-13T23:24:33.163+0000] {processor.py:157} INFO - Started process (PID=438) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:24:33.164+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:24:33.166+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:24:33.166+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:24:33.172+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:24:33.174+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:24:33.183+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:24:33.203+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:24:33.203+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:24:33.210+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:24:33.210+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:24:33.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.065 seconds
[2025-05-13T23:25:03.604+0000] {processor.py:157} INFO - Started process (PID=448) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:25:03.605+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:25:03.607+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:25:03.607+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:25:03.628+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:25:03.634+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:25:03.646+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:25:03.674+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:25:03.674+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:25:03.686+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:25:03.685+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:25:03.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.099 seconds
[2025-05-13T23:25:34.014+0000] {processor.py:157} INFO - Started process (PID=458) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:25:34.016+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:25:34.017+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:25:34.017+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:25:34.021+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:25:34.023+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:25:34.032+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:25:34.052+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:25:34.051+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:25:34.058+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:25:34.058+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:25:34.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.058 seconds
[2025-05-13T23:26:04.392+0000] {processor.py:157} INFO - Started process (PID=468) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:26:04.393+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:26:04.394+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:26:04.394+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:26:04.398+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:26:04.399+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:26:04.410+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:26:04.431+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:26:04.431+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:26:04.439+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:26:04.439+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:26:04.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.063 seconds
[2025-05-13T23:26:34.763+0000] {processor.py:157} INFO - Started process (PID=478) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:26:34.764+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:26:34.765+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:26:34.765+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:26:34.769+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:26:34.770+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:26:34.781+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:26:34.802+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:26:34.802+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:26:34.809+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:26:34.809+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:26:34.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.062 seconds
[2025-05-13T23:27:05.172+0000] {processor.py:157} INFO - Started process (PID=488) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:27:05.174+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:27:05.176+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:27:05.175+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:27:05.180+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:27:05.181+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:27:05.189+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:27:05.207+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:27:05.207+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:27:05.214+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:27:05.214+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:27:05.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.056 seconds
[2025-05-13T23:27:35.587+0000] {processor.py:157} INFO - Started process (PID=498) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:27:35.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:27:35.590+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:27:35.590+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:27:35.595+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:27:35.596+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:27:35.606+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:27:35.624+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:27:35.624+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:27:35.631+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:27:35.631+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:27:35.644+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.063 seconds
[2025-05-13T23:28:05.971+0000] {processor.py:157} INFO - Started process (PID=508) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:28:05.972+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:28:05.973+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:28:05.972+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:28:05.977+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:28:05.979+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:28:05.998+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:28:06.036+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:28:06.036+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:28:06.049+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:28:06.049+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:28:06.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.094 seconds
[2025-05-13T23:28:36.396+0000] {processor.py:157} INFO - Started process (PID=518) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:28:36.398+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:28:36.400+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:28:36.400+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:28:36.407+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:28:36.409+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:28:36.419+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:28:36.442+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:28:36.442+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:28:36.449+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:28:36.449+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:28:36.457+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.071 seconds
[2025-05-13T23:29:06.763+0000] {processor.py:157} INFO - Started process (PID=528) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:29:06.765+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:29:06.767+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:29:06.767+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:29:06.775+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:29:06.777+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:29:06.796+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:29:06.820+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:29:06.820+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:29:06.830+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:29:06.829+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:29:06.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.089 seconds
[2025-05-13T23:29:37.197+0000] {processor.py:157} INFO - Started process (PID=538) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:29:37.200+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:29:37.202+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:29:37.201+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:29:37.208+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:29:37.210+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:29:37.220+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:29:37.241+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:29:37.241+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:29:37.247+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:29:37.247+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:29:37.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.074 seconds
[2025-05-13T23:30:07.630+0000] {processor.py:157} INFO - Started process (PID=548) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:30:07.632+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:30:07.632+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:30:07.632+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:30:07.636+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:30:07.637+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:30:07.644+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:30:07.662+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:30:07.662+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:30:07.673+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:30:07.673+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:30:07.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.061 seconds
[2025-05-13T23:30:38.002+0000] {processor.py:157} INFO - Started process (PID=558) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:30:38.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:30:38.004+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:30:38.004+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:30:38.009+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:30:38.011+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:30:38.022+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:30:38.050+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:30:38.050+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:30:38.058+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:30:38.058+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:30:38.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.073 seconds
[2025-05-13T23:31:08.376+0000] {processor.py:157} INFO - Started process (PID=568) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:31:08.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:31:08.379+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:31:08.378+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:31:08.382+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:31:08.384+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:31:08.392+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:31:08.407+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:31:08.407+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:31:08.414+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:31:08.414+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:31:08.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.054 seconds
[2025-05-13T23:31:38.765+0000] {processor.py:157} INFO - Started process (PID=578) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:31:38.765+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:31:38.767+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:31:38.766+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:31:38.771+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:31:38.772+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:31:38.784+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:31:38.818+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:31:38.818+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:31:38.831+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:31:38.831+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:31:38.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.085 seconds
[2025-05-13T23:32:09.212+0000] {processor.py:157} INFO - Started process (PID=588) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:32:09.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:32:09.215+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:32:09.215+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:32:09.219+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:32:09.220+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:32:09.230+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:32:09.253+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:32:09.253+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:32:09.262+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:32:09.262+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:32:09.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.065 seconds
[2025-05-13T23:32:39.691+0000] {processor.py:157} INFO - Started process (PID=598) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:32:39.694+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:32:39.696+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:32:39.695+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:32:39.701+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:32:39.703+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:32:39.718+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:32:39.748+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:32:39.748+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:32:39.758+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:32:39.758+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:32:39.774+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.091 seconds
[2025-05-13T23:33:10.199+0000] {processor.py:157} INFO - Started process (PID=608) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:33:10.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:33:10.203+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:33:10.202+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:33:10.208+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:33:10.210+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:33:10.221+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:33:10.248+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:33:10.248+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:33:10.265+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:33:10.265+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:33:10.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.112 seconds
[2025-05-13T23:33:40.662+0000] {processor.py:157} INFO - Started process (PID=618) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:33:40.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:33:40.665+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:33:40.665+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:33:40.670+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:33:40.672+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:33:40.684+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:33:40.707+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:33:40.707+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:33:40.715+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:33:40.715+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:33:40.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.069 seconds
[2025-05-13T23:34:11.095+0000] {processor.py:157} INFO - Started process (PID=628) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:34:11.103+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:34:11.106+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:34:11.105+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:34:11.112+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:34:11.114+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:34:11.137+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:34:11.161+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:34:11.160+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:34:11.169+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:34:11.169+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:34:11.178+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.089 seconds
[2025-05-13T23:34:41.523+0000] {processor.py:157} INFO - Started process (PID=638) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:34:41.525+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:34:41.528+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:34:41.527+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:34:41.534+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:34:41.540+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:34:41.554+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:34:41.579+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:34:41.579+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:34:41.588+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:34:41.588+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:34:41.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.098 seconds
[2025-05-13T23:35:11.971+0000] {processor.py:157} INFO - Started process (PID=648) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:35:11.972+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:35:11.974+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:35:11.974+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:35:11.978+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:35:11.979+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:35:11.986+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:35:12.003+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:35:12.003+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:35:12.010+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:35:12.010+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:35:12.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.055 seconds
[2025-05-13T23:35:42.359+0000] {processor.py:157} INFO - Started process (PID=658) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:35:42.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:35:42.363+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:35:42.362+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:35:42.368+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:35:42.370+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:35:42.386+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:35:42.423+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:35:42.423+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:35:42.432+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:35:42.432+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:35:42.441+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.091 seconds
[2025-05-13T23:36:12.862+0000] {processor.py:157} INFO - Started process (PID=668) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:36:12.864+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:36:12.866+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:36:12.865+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:36:12.871+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:36:12.873+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:36:12.888+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:36:12.933+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:36:12.933+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:36:12.943+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:36:12.943+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:36:12.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.108 seconds
[2025-05-13T23:36:43.334+0000] {processor.py:157} INFO - Started process (PID=678) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:36:43.336+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:36:43.340+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:36:43.339+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:36:43.344+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:36:43.347+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:36:43.363+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:36:43.387+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:36:43.387+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:36:43.397+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:36:43.397+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:36:43.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.084 seconds
[2025-05-13T23:37:13.777+0000] {processor.py:157} INFO - Started process (PID=688) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:37:13.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:37:13.780+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:37:13.780+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:37:13.785+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:37:13.787+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:37:13.798+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:37:13.820+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:37:13.820+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:37:13.828+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:37:13.828+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:37:13.840+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.070 seconds
[2025-05-13T23:37:44.217+0000] {processor.py:157} INFO - Started process (PID=698) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:37:44.223+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:37:44.229+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:37:44.226+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:37:44.239+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:37:44.242+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:37:44.257+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:37:44.284+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:37:44.284+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:37:44.293+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:37:44.293+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:37:44.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.095 seconds
[2025-05-13T23:38:14.682+0000] {processor.py:157} INFO - Started process (PID=708) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:38:14.683+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:38:14.684+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:38:14.684+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:38:14.688+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:38:14.690+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:38:14.700+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:38:14.732+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:38:14.732+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:38:14.740+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:38:14.740+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:38:14.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.075 seconds
[2025-05-13T23:38:45.114+0000] {processor.py:157} INFO - Started process (PID=718) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:38:45.116+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:38:45.120+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:38:45.118+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:38:45.125+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:38:45.128+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:38:45.158+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:38:45.191+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:38:45.191+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:38:45.199+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:38:45.199+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:38:45.208+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.109 seconds
[2025-05-13T23:39:15.582+0000] {processor.py:157} INFO - Started process (PID=728) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:39:15.584+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:39:15.585+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:39:15.585+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:39:15.589+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:39:15.592+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:39:15.601+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:39:15.619+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:39:15.619+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:39:15.626+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:39:15.626+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:39:15.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.056 seconds
[2025-05-13T23:39:46.023+0000] {processor.py:157} INFO - Started process (PID=738) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:39:46.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:39:46.027+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:39:46.026+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:39:46.035+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:39:46.040+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:39:46.050+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:39:46.071+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:39:46.071+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:39:46.083+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:39:46.083+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:39:46.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.076 seconds
[2025-05-13T23:40:16.440+0000] {processor.py:157} INFO - Started process (PID=748) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:40:16.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:40:16.444+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:40:16.444+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:40:16.448+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:40:16.450+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:40:16.458+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:40:16.476+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:40:16.476+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:40:16.483+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:40:16.483+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:40:16.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.056 seconds
[2025-05-13T23:40:46.820+0000] {processor.py:157} INFO - Started process (PID=758) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:40:46.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:40:46.823+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:40:46.822+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:40:46.826+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:40:46.828+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:40:46.846+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:40:46.866+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:40:46.865+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:40:46.874+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:40:46.873+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:40:46.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.068 seconds
[2025-05-13T23:41:17.251+0000] {processor.py:157} INFO - Started process (PID=768) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:41:17.254+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:41:17.255+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:41:17.255+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:41:17.260+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:41:17.262+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:41:17.270+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:41:17.290+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:41:17.290+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:41:17.297+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:41:17.297+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:41:17.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.061 seconds
[2025-05-13T23:41:47.687+0000] {processor.py:157} INFO - Started process (PID=778) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:41:47.689+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:41:47.691+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:41:47.690+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:41:47.696+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:41:47.698+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:41:47.710+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:41:47.744+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:41:47.744+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:41:47.753+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:41:47.752+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:41:47.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.084 seconds
[2025-05-13T23:42:18.141+0000] {processor.py:157} INFO - Started process (PID=788) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:42:18.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:42:18.144+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:42:18.144+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:42:18.158+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:42:18.161+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:42:18.173+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:42:18.202+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:42:18.202+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:42:18.218+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:42:18.218+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:42:18.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.096 seconds
[2025-05-13T23:42:48.654+0000] {processor.py:157} INFO - Started process (PID=798) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:42:48.656+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:42:48.657+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:42:48.656+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:42:48.662+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:42:48.664+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:42:48.677+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:42:48.702+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:42:48.702+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:42:48.711+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:42:48.711+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:42:48.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.082 seconds
[2025-05-13T23:43:19.101+0000] {processor.py:157} INFO - Started process (PID=808) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:43:19.103+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:43:19.104+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:43:19.104+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:43:19.108+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:43:19.109+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:43:19.117+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:43:19.135+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:43:19.135+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:43:19.142+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:43:19.142+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:43:19.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.055 seconds
[2025-05-13T23:43:49.540+0000] {processor.py:157} INFO - Started process (PID=818) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:43:49.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:43:49.543+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:43:49.543+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:43:49.547+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:43:49.549+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:43:49.559+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:43:49.599+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:43:49.598+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:43:49.608+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:43:49.607+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:43:49.619+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.088 seconds
[2025-05-13T23:44:20.029+0000] {processor.py:157} INFO - Started process (PID=828) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:44:20.031+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:44:20.034+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:44:20.033+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:44:20.039+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:44:20.041+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:44:20.051+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:44:20.074+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:44:20.073+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:44:20.082+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:44:20.082+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:44:20.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.082 seconds
[2025-05-13T23:44:50.455+0000] {processor.py:157} INFO - Started process (PID=838) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:44:50.457+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:44:50.458+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:44:50.458+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:44:50.462+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:44:50.465+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:44:50.485+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:44:50.537+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:44:50.537+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:44:50.546+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:44:50.546+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:44:50.556+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.109 seconds
[2025-05-13T23:45:20.882+0000] {processor.py:157} INFO - Started process (PID=848) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:45:20.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:45:20.885+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:45:20.885+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:45:20.889+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:45:20.891+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:45:20.900+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:45:20.920+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:45:20.920+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:45:20.927+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:45:20.927+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:45:20.935+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.060 seconds
[2025-05-13T23:45:51.287+0000] {processor.py:157} INFO - Started process (PID=858) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:45:51.289+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:45:51.290+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:45:51.289+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:45:51.296+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:45:51.300+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:45:51.311+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:45:51.339+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:45:51.339+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:45:51.348+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:45:51.348+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:45:51.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.078 seconds
[2025-05-13T23:46:21.747+0000] {processor.py:157} INFO - Started process (PID=868) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:46:21.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:46:21.751+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:46:21.750+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:46:21.757+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:46:21.759+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:46:21.768+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:46:21.786+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:46:21.786+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:46:21.792+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:46:21.792+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:46:21.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.060 seconds
[2025-05-13T23:46:52.142+0000] {processor.py:157} INFO - Started process (PID=878) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:46:52.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:46:52.144+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:46:52.143+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:46:52.147+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:46:52.149+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:46:52.159+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:46:52.183+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:46:52.183+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:46:52.192+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:46:52.192+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:46:52.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.080 seconds
[2025-05-13T23:47:22.610+0000] {processor.py:157} INFO - Started process (PID=888) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:47:22.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:47:22.613+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:47:22.613+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:47:22.618+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:47:22.619+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:47:22.628+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:47:22.645+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:47:22.645+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:47:22.652+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:47:22.651+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:47:22.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.057 seconds
[2025-05-13T23:47:52.999+0000] {processor.py:157} INFO - Started process (PID=898) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:47:53.001+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:47:53.002+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:47:53.002+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:47:53.006+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:47:53.007+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:47:53.014+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:47:53.035+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:47:53.035+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:47:53.050+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:47:53.050+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:47:53.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.067 seconds
[2025-05-13T23:48:23.373+0000] {processor.py:157} INFO - Started process (PID=908) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:48:23.374+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:48:23.376+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:48:23.375+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:48:23.379+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:48:23.380+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:48:23.389+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:48:23.407+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:48:23.407+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:48:23.413+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:48:23.413+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:48:23.421+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.053 seconds
[2025-05-13T23:48:53.769+0000] {processor.py:157} INFO - Started process (PID=918) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:48:53.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:48:53.773+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:48:53.772+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:48:53.778+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:48:53.780+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:48:53.790+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:48:53.812+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:48:53.812+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:48:53.820+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:48:53.820+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:48:53.830+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.068 seconds
[2025-05-13T23:49:24.201+0000] {processor.py:157} INFO - Started process (PID=928) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:49:24.204+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:49:24.205+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:49:24.205+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:49:24.210+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:49:24.213+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:49:24.222+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:49:24.239+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:49:24.239+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:49:24.245+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:49:24.245+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:49:24.253+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.062 seconds
[2025-05-13T23:49:54.616+0000] {processor.py:157} INFO - Started process (PID=938) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:49:54.618+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:49:54.619+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:49:54.618+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:49:54.623+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:49:54.624+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:49:54.641+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:49:54.668+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:49:54.668+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:49:54.676+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:49:54.676+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:49:54.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.076 seconds
[2025-05-13T23:50:25.022+0000] {processor.py:157} INFO - Started process (PID=948) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:50:25.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:50:25.023+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:50:25.023+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:50:25.026+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:50:25.027+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:50:25.032+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:50:25.048+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:50:25.048+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:50:25.054+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:50:25.054+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:50:25.063+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.046 seconds
[2025-05-13T23:50:55.426+0000] {processor.py:157} INFO - Started process (PID=958) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:50:55.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:50:55.429+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:50:55.428+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:50:55.436+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:50:55.439+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:50:55.446+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:50:55.460+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:50:55.460+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:50:55.466+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:50:55.466+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:50:55.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.058 seconds
[2025-05-13T23:51:25.827+0000] {processor.py:157} INFO - Started process (PID=968) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:51:25.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:51:25.829+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:51:25.829+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:51:25.833+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:51:25.835+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:51:25.852+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:51:25.881+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:51:25.881+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:51:25.889+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:51:25.888+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:51:25.898+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.078 seconds
[2025-05-13T23:51:56.243+0000] {processor.py:157} INFO - Started process (PID=978) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:51:56.245+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:51:56.247+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:51:56.246+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:51:56.250+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:51:56.251+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:51:56.260+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:51:56.279+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:51:56.279+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:51:56.287+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:51:56.286+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:51:56.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.058 seconds
[2025-05-13T23:52:26.689+0000] {processor.py:157} INFO - Started process (PID=988) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:52:26.690+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:52:26.691+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:52:26.691+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:52:26.695+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:52:26.697+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:52:26.705+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:52:26.727+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:52:26.727+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:52:26.735+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:52:26.735+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:52:26.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.062 seconds
[2025-05-13T23:52:57.133+0000] {processor.py:157} INFO - Started process (PID=998) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:52:57.136+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:52:57.139+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:52:57.138+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:52:57.150+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:52:57.153+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:52:57.166+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:52:57.199+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:52:57.199+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:52:57.209+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:52:57.209+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:52:57.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.097 seconds
[2025-05-13T23:53:27.627+0000] {processor.py:157} INFO - Started process (PID=1008) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:53:27.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:53:27.631+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:53:27.630+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:53:27.635+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:53:27.636+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:53:27.642+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:53:27.659+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:53:27.659+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:53:27.665+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:53:27.665+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:53:27.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.054 seconds
[2025-05-13T23:53:58.026+0000] {processor.py:157} INFO - Started process (PID=1018) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:53:58.027+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:53:58.028+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:53:58.028+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:53:58.032+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:53:58.034+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:53:58.044+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:53:58.078+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:53:58.078+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:53:58.087+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:53:58.087+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:53:58.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.077 seconds
[2025-05-13T23:54:28.445+0000] {processor.py:157} INFO - Started process (PID=1028) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:54:28.447+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:54:28.448+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:54:28.448+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:54:28.452+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:54:28.454+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:54:28.462+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:54:28.482+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:54:28.482+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:54:28.488+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:54:28.488+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:54:28.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.057 seconds
[2025-05-13T23:54:58.875+0000] {processor.py:157} INFO - Started process (PID=1038) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:54:58.879+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:54:58.882+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:54:58.880+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:54:58.891+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:54:58.894+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:54:58.906+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:54:58.932+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:54:58.932+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:54:58.942+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:54:58.942+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:54:58.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.082 seconds
[2025-05-13T23:55:29.299+0000] {processor.py:157} INFO - Started process (PID=1048) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:55:29.301+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:55:29.302+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:55:29.302+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:55:29.306+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:55:29.308+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:55:29.316+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:55:29.333+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:55:29.333+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:55:29.339+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:55:29.339+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:55:29.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.053 seconds
[2025-05-13T23:55:59.739+0000] {processor.py:157} INFO - Started process (PID=1058) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:55:59.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:55:59.743+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:55:59.743+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:55:59.749+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:55:59.753+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:55:59.766+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:55:59.789+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:55:59.789+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:55:59.797+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:55:59.797+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:55:59.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.077 seconds
[2025-05-13T23:56:30.104+0000] {processor.py:157} INFO - Started process (PID=1068) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:56:30.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:56:30.106+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:56:30.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:56:30.109+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:56:30.110+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:56:30.116+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:56:30.133+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:56:30.133+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:56:30.142+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:56:30.142+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:56:30.155+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.055 seconds
[2025-05-13T23:57:00.549+0000] {processor.py:157} INFO - Started process (PID=1078) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:57:00.550+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:57:00.551+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:57:00.551+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:57:00.556+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:57:00.557+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:57:00.567+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:57:00.596+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:57:00.595+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:57:00.605+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:57:00.605+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:57:00.615+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.090 seconds
[2025-05-13T23:57:30.976+0000] {processor.py:157} INFO - Started process (PID=1088) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:57:30.977+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:57:30.978+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:57:30.978+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:57:30.982+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:57:30.984+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:57:30.994+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:57:31.020+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:57:31.020+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:57:31.030+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:57:31.030+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:57:31.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.069 seconds
[2025-05-13T23:58:01.342+0000] {processor.py:157} INFO - Started process (PID=1098) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:58:01.346+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:58:01.348+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:58:01.348+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:58:01.354+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:58:01.355+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:58:01.365+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:58:01.390+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:58:01.390+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:58:01.400+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:58:01.399+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:58:01.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.077 seconds
[2025-05-13T23:58:31.804+0000] {processor.py:157} INFO - Started process (PID=1108) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:58:31.806+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:58:31.807+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:58:31.806+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:58:31.810+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:58:31.812+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:58:31.820+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:58:31.839+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:58:31.839+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:58:31.846+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:58:31.846+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:58:31.855+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.059 seconds
[2025-05-13T23:59:02.201+0000] {processor.py:157} INFO - Started process (PID=1118) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:59:02.203+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:59:02.204+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:59:02.203+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:59:02.206+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:59:02.208+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:59:02.214+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:59:02.232+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:59:02.232+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:59:02.240+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:59:02.240+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:59:02.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.052 seconds
[2025-05-13T23:59:32.637+0000] {processor.py:157} INFO - Started process (PID=1128) to work on /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:59:32.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_redfin_to_s3.py for tasks to queue
[2025-05-13T23:59:32.645+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:59:32.642+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:59:32.651+0000] {logging_mixin.py:154} INFO - ✅ DAG upload_local_to_s3.py loaded.
[2025-05-13T23:59:32.653+0000] {logging_mixin.py:154} INFO - ❌ Import failed in DAG: No module named 'data'
[2025-05-13T23:59:32.665+0000] {processor.py:839} INFO - DAG(s) dict_keys(['upload_local_to_s3']) retrieved from /opt/airflow/dags/etl_redfin_to_s3.py
[2025-05-13T23:59:32.695+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:59:32.695+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-13T23:59:32.704+0000] {logging_mixin.py:154} INFO - [2025-05-13T23:59:32.704+0000] {dag.py:3722} INFO - Setting next_dagrun for upload_local_to_s3 to None, run_after=None
[2025-05-13T23:59:32.714+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_redfin_to_s3.py took 0.090 seconds
